services:
  opennourish-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./persistent:/app/persistent
    env_file:
      - ./.env

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # This now correctly maps a sub-directory for the self-signed certs,
      # matching the volume mount in the TrueNAS compose file.
      - ./persistent/nginx_certs:/etc/nginx/certs
    depends_on:
      - opennourish-app