services:
  opennourish-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./persistent:/app/persistent
    env_file:
      - ./.env

  nginx:
    build:
      context: ./nginx # <-- Build the image from the nginx directory
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # The config volume is GONE, but the data volume for certs REMAINS
      - ./persistent:/data:ro
    depends_on:
      - opennourish-app