services:
  opennourish-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Map the local './persistent' directory to '/app/persistent' in the container
      - ./persistent:/app/persistent
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Map the same local directory for certs, read-only
      - ./persistent:/data:ro
    depends_on:
      - opennourish-app