# Build both services defined in the compose file
#docker compose build

# Tag both images for your private registry
#docker tag opennourish-opennourish-app:latest saturn.ms4f.net:30095/opennourish-app:latest
#docker tag opennourish-nginx:latest saturn.ms4f.net:30095/opennourish-nginx:latest

# Push both images
#docker push saturn.ms4f.net:30095/opennourish-app:latest
#docker push saturn.ms4f.net:30095/opennourish-nginx:latest

#use this part in TrueNAS:
services:
  opennourish-app:
    image: saturn.ms4f.net:30095/opennourish-app:latest
    restart: unless-stopped
    environment:
      - SECRET_KEY=YourSuperStrongSecretKeyGoesHere
      - SEED_DEV_DATA=true
    volumes:
      - /mnt/data-pool/opennourish:/app/persistent

  nginx:
    image: saturn.ms4f.net:30095/opennourish-nginx:latest
    restart: unless-stopped
    ports:
      - "18080:80"
      - "18443:443"
    environment:
      # These variables tell the entrypoint script where to find the real certs.
      # Users can change these values if their certs are named differently.
      # Leave these blank or unset them to use the self-signed fallback.
      REAL_CERT_PATH: /etc/certificates/LEProduction.crt
      REAL_KEY_PATH: /etc/certificates/LEProduction.key
    volumes:
      # 1. Mount the TrueNAS certificates directory so the container can see it.
      - /etc/certificates:/etc/certificates:ro
      # 2. Mount a persistent directory for Nginx to store its fallback certs.
      - /mnt/data-pool/opennourish/nginx_certs:/etc/nginx/certs
    depends_on:
      - opennourish-app