"""Add detailed recipe portions

Revision ID: 0c464220f242
Revises: d84b04152f44
Create Date: 2025-07-05 20:32:16.559755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c464220f242'
down_revision = 'd84b04152f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_portions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('measure_unit_description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('modifier', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('full_description', sa.String(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_portions', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('full_description')
        batch_op.drop_column('modifier')
        batch_op.drop_column('measure_unit_description')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
