"""add recipe_id to recipe_ingredient

Revision ID: 1730eac5d10b
Revises: 4df87ee8e32b
Create Date: 2025-07-05 10:53:35.192161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1730eac5d10b'
down_revision = '4df87ee8e32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id_link', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_recipe_ingredient_recipe_id_link', 'recipes', ['recipe_id_link'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recipe_id_link')

    # ### end Alembic commands ###
