"""Add age, gender, and height to User model

Revision ID: 29af989a39cd
Revises: ed46d6d10d28
Create Date: 2025-07-05 23:10:16.541071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29af989a39cd'
down_revision = 'ed46d6d10d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('height_cm')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')

    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.drop_column('height_cm')

    # ### end Alembic commands ###
