"""Remove initial_weight_kg and initial_body_fat_percentage from UserGoal

Revision ID: 3491563f7e67
Revises: a881c846e70c
Create Date: 2025-07-06 18:42:57.329879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3491563f7e67'
down_revision = 'a881c846e70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_column('initial_weight_kg')
        batch_op.drop_column('initial_body_fat_percentage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_body_fat_percentage', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('initial_weight_kg', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
