"""Add seq_num to RecipeIngredient

Revision ID: 3978a31de65b
Revises: cb243cbec50e
Create Date: 2025-08-03 21:09:22.595438

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3978a31de65b"
down_revision = "cb243cbec50e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_ingredients", schema=None) as batch_op:
        batch_op.add_column(sa.Column("seq_num", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe_ingredients", schema=None) as batch_op:
        batch_op.drop_column("seq_num")

    # ### end Alembic commands ###
