"""Set MyFood nutritional fields to non-nullable with default 0.0

Revision ID: 4df87ee8e32b
Revises: 93478c54a431
Create Date: 2025-07-05 09:34:12.405282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df87ee8e32b'
down_revision = '93478c54a431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Set existing NULL values to 0.0 before making columns non-nullable
    op.execute("UPDATE my_foods SET calories_per_100g = 0.0 WHERE calories_per_100g IS NULL")
    op.execute("UPDATE my_foods SET protein_per_100g = 0.0 WHERE protein_per_100g IS NULL")
    op.execute("UPDATE my_foods SET carbs_per_100g = 0.0 WHERE carbs_per_100g IS NULL")
    op.execute("UPDATE my_foods SET fat_per_100g = 0.0 WHERE fat_per_100g IS NULL")
    op.execute("UPDATE my_foods SET saturated_fat_per_100g = 0.0 WHERE saturated_fat_per_100g IS NULL")
    op.execute("UPDATE my_foods SET trans_fat_per_100g = 0.0 WHERE trans_fat_per_100g IS NULL")
    op.execute("UPDATE my_foods SET cholesterol_mg_per_100g = 0.0 WHERE cholesterol_mg_per_100g IS NULL")
    op.execute("UPDATE my_foods SET sodium_mg_per_100g = 0.0 WHERE sodium_mg_per_100g IS NULL")
    op.execute("UPDATE my_foods SET fiber_per_100g = 0.0 WHERE fiber_per_100g IS NULL")
    op.execute("UPDATE my_foods SET sugars_per_100g = 0.0 WHERE sugars_per_100g IS NULL")
    op.execute("UPDATE my_foods SET vitamin_d_mcg_per_100g = 0.0 WHERE vitamin_d_mcg_per_100g IS NULL")
    op.execute("UPDATE my_foods SET calcium_mg_per_100g = 0.0 WHERE calcium_mg_per_100g IS NULL")
    op.execute("UPDATE my_foods SET iron_mg_per_100g = 0.0 WHERE iron_mg_per_100g IS NULL")
    op.execute("UPDATE my_foods SET potassium_mg_per_100g = 0.0 WHERE potassium_mg_per_100g IS NULL")

    with op.batch_alter_table('my_foods', schema=None) as batch_op:
        batch_op.alter_column('calories_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('protein_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('carbs_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('fat_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('saturated_fat_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('trans_fat_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('cholesterol_mg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sodium_mg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('fiber_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('sugars_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('vitamin_d_mcg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('calcium_mg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('iron_mg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('potassium_mg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_foods', schema=None) as batch_op:
        batch_op.alter_column('potassium_mg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('iron_mg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('calcium_mg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('vitamin_d_mcg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('sugars_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('fiber_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('sodium_mg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cholesterol_mg_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('trans_fat_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('saturated_fat_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('fat_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('carbs_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('protein_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('calories_per_100g',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
