"""Add has_completed_onboarding to User model

Revision ID: 4f127cdd65a3
Revises: eb3d545c4cc1
Create Date: 2025-07-18 17:28:54.138816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f127cdd65a3'
down_revision = 'eb3d545c4cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # 1. Add the column as nullable first
        batch_op.add_column(sa.Column('has_completed_onboarding', sa.Boolean(), nullable=True))

    # 2. Update existing users to set has_completed_onboarding to True
    op.execute("UPDATE users SET has_completed_onboarding = 1") # 1 for True in SQLite

    with op.batch_alter_table('users', schema=None) as batch_op:
        # 3. Alter the column to be non-nullable
        batch_op.alter_column('has_completed_onboarding',
                              existing_type=sa.Boolean(),
                              nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_completed_onboarding')

    # ### end Alembic commands ###
