"""Add is_placeholder to MyFood

Revision ID: 4ff671f5bcdc
Revises: 8f01092d5559
Create Date: 2025-09-14 19:14:51.597003

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ff671f5bcdc"
down_revision = "8f01092d5559"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("my_foods", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_placeholder", sa.Boolean(), nullable=False, server_default="0"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("my_foods", schema=None) as batch_op:
        batch_op.drop_column("is_placeholder")

    # ### end Alembic commands ###
