"""Add goal_modifier and diet_preset to UserGoal

Revision ID: 560c919e1aa1
Revises: 16ecd221bbfc
Create Date: 2025-07-23 19:14:15.988080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560c919e1aa1'
down_revision = '16ecd221bbfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_modifier', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('diet_preset', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_column('diet_preset')
        batch_op.drop_column('goal_modifier')

    # ### end Alembic commands ###
