"""Add week_start_day to User model

Revision ID: 56cdeb4e1f26
Revises: e13c9dcf8865
Create Date: 2025-07-29 18:44:54.340392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cdeb4e1f26'
down_revision = 'e13c9dcf8865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_start_day', sa.String(length=10), nullable=False, server_default='Monday'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('week_start_day')

    # ### end Alembic commands ###
