"""Add user preference settings

Revision ID: 5fd454700e4f
Revises: 6cbf733e275b
Create Date: 2025-07-13 20:27:52.131611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd454700e4f'
down_revision = '6cbf733e275b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('navbar_preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('diary_default_view', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('diary_default_view')
        batch_op.drop_column('navbar_preference')

    # ### end Alembic commands ###
