"""add detailed nutritional info to myfood

Revision ID: 6ae9d776bb7e
Revises: dd3833ffba29
Create Date: 2025-07-04 10:33:17.182191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae9d776bb7e'
down_revision = 'dd3833ffba29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saturated_fat_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trans_fat_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cholesterol_mg_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sodium_mg_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fiber_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sugars_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vitamin_d_mcg_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calcium_mg_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('iron_mg_per_100g', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('potassium_mg_per_100g', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_foods', schema=None) as batch_op:
        batch_op.drop_column('potassium_mg_per_100g')
        batch_op.drop_column('iron_mg_per_100g')
        batch_op.drop_column('calcium_mg_per_100g')
        batch_op.drop_column('vitamin_d_mcg_per_100g')
        batch_op.drop_column('sugars_per_100g')
        batch_op.drop_column('fiber_per_100g')
        batch_op.drop_column('sodium_mg_per_100g')
        batch_op.drop_column('cholesterol_mg_per_100g')
        batch_op.drop_column('trans_fat_per_100g')
        batch_op.drop_column('saturated_fat_per_100g')

    # ### end Alembic commands ###
