"""Add serving_type and portion_id_fk to RecipeIngredient

Revision ID: 6c72ddf5a3a2
Revises: 66f951082e06
Create Date: 2025-07-11 15:52:15.116594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c72ddf5a3a2'
down_revision = '66f951082e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serving_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('portion_id_fk', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_recipe_ingredient_portion_id', 'portions', ['portion_id_fk'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('portion_id_fk')
        batch_op.drop_column('serving_type')

    # ### end Alembic commands ###
