"""add serving_type to dailylog

Revision ID: 6d1875140abe
Revises: 6ae9d776bb7e
Create Date: 2025-07-04 10:56:16.963217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1875140abe'
down_revision = '6ae9d776bb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serving_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_column('serving_type')

    # ### end Alembic commands ###
