"""add exercise goals to usergoal

Revision ID: 8400cf214355
Revises: d2d38616b469
Create Date: 2025-07-07 18:44:07.162647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8400cf214355'
down_revision = 'd2d38616b469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_burned_goal_weekly', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('exercises_per_week_goal', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('minutes_per_exercise_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_column('minutes_per_exercise_goal')
        batch_op.drop_column('exercises_per_week_goal')
        batch_op.drop_column('calories_burned_goal_weekly')

    # ### end Alembic commands ###
