"""add is_key_user

Revision ID: 865673f22006
Revises: 56cdeb4e1f26
Create Date: 2025-07-31 17:30:09.691907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865673f22006'
down_revision = '56cdeb4e1f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_key_user', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_key_user')

    # ### end Alembic commands ###
