"""Add user_id to FoodCategory and make code nullable

Revision ID: 8f01092d5559
Revises: 9dc6a1eef6f6
Create Date: 2025-09-03 22:41:37.438517

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f01092d5559"
down_revision = "9dc6a1eef6f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("food_category", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.alter_column("code", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_unique_constraint(
            "_user_category_uc", ["user_id", "description"]
        )
        batch_op.create_foreign_key(
            "fk_food_category_user_id", "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("food_category", schema=None) as batch_op:
        batch_op.drop_constraint("fk_food_category_user_id", type_="foreignkey")
        batch_op.drop_constraint("_user_category_uc", type_="unique")
        batch_op.alter_column("code", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
