"""Add nutrition cache columns to Recipe model

Revision ID: 8f6c7f357a33
Revises: 0f8f437c9b05
Create Date: 2025-07-15 21:13:30.626348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6c7f357a33'
down_revision = '0f8f437c9b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('protein_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('carbs_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('fat_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('saturated_fat_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('trans_fat_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('cholesterol_mg_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('sodium_mg_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('fiber_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('sugars_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('vitamin_d_mcg_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('calcium_mg_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('iron_mg_per_100g', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('potassium_mg_per_100g', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('potassium_mg_per_100g')
        batch_op.drop_column('iron_mg_per_100g')
        batch_op.drop_column('calcium_mg_per_100g')
        batch_op.drop_column('vitamin_d_mcg_per_100g')
        batch_op.drop_column('sugars_per_100g')
        batch_op.drop_column('fiber_per_100g')
        batch_op.drop_column('sodium_mg_per_100g')
        batch_op.drop_column('cholesterol_mg_per_100g')
        batch_op.drop_column('trans_fat_per_100g')
        batch_op.drop_column('saturated_fat_per_100g')
        batch_op.drop_column('fat_per_100g')
        batch_op.drop_column('carbs_per_100g')
        batch_op.drop_column('protein_per_100g')
        batch_op.drop_column('calories_per_100g')

    # ### end Alembic commands ###
