"""Add missing columns to check_ins table

Revision ID: 9321bdf4aae0
Revises: cc40ca3e3bfa
Create Date: 2025-07-02 20:43:40.064408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9321bdf4aae0'
down_revision: Union[str, Sequence[str], None] = 'cc40ca3e3bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_fat_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('waist_cm', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.drop_column('waist_cm')
        batch_op.drop_column('body_fat_percentage')

    # ### end Alembic commands ###