"""Allow null user_id in my_meals for anonymization

Revision ID: 9dc6a1eef6f6
Revises: b2a84814143e
Create Date: 2025-08-17 17:33:08.735912

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9dc6a1eef6f6"
down_revision = "b2a84814143e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("my_meals", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("my_meals", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
