"""Add usage_count to MyMeal

Revision ID: a23f40ce09da
Revises: a4c336779ea6
Create Date: 2025-07-05 18:46:01.675987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23f40ce09da'
down_revision = 'a4c336779ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_meals', schema=None) as batch_op:
        batch_op.drop_column('usage_count')

    # ### end Alembic commands ###
