"""Add my_meal_id to DailyLog

Revision ID: a4c336779ea6
Revises: 6889307a57b4
Create Date: 2025-07-05 18:39:12.837960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c336779ea6'
down_revision = '6889307a57b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_meal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_daily_logs_my_meal_id_my_meals', 'my_meals', ['my_meal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('my_meal_id')

    # ### end Alembic commands ###
