"""Add initial_weight_kg and initial_body_fat_percentage to UserGoal

Revision ID: a881c846e70c
Revises: c6a0c982ece4
Create Date: 2025-07-06 18:28:43.191810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a881c846e70c'
down_revision = 'c6a0c982ece4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('initial_body_fat_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_goals', schema=None) as batch_op:
        batch_op.drop_column('initial_body_fat_percentage')
        batch_op.drop_column('initial_weight_kg')

    # ### end Alembic commands ###
