"""Remove my_meal_id from DailyLog

Revision ID: addc3b50d28a
Revises: a23f40ce09da
Create Date: 2025-07-05 18:47:24.517535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'addc3b50d28a'
down_revision = 'a23f40ce09da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_daily_logs_my_meal_id_my_meals'), type_='foreignkey')
        batch_op.drop_column('my_meal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_meal_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_daily_logs_my_meal_id_my_meals'), 'my_meals', ['my_meal_id'], ['id'])

    # ### end Alembic commands ###
