"""add ingredients and portions to myfood

Revision ID: b00ba25e6237
Revises: 6d1875140abe
Create Date: 2025-07-04 11:10:09.167858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00ba25e6237'
down_revision = '6d1875140abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_portions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('my_food_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('gram_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['my_food_id'], ['my_foods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('my_foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_foods', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    op.drop_table('my_portions')
    # ### end Alembic commands ###
