"""Add final_weight_grams to Recipe model

Revision ID: b2a84814143e
Revises: 3978a31de65b
Create Date: 2025-08-10 18:53:36.937783

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b2a84814143e"
down_revision = "3978a31de65b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("final_weight_grams", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipes", schema=None) as batch_op:
        batch_op.drop_column("final_weight_grams")

    # ### end Alembic commands ###
