"""Update UnifiedPortion model and Food relationship

Revision ID: c6a0c982ece4
Revises: ac2fb6ec93ec
Create Date: 2025-07-06 18:22:44.781660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a0c982ece4'
down_revision = 'ac2fb6ec93ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portions_fdc_id'), ['fdc_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portions_fdc_id'))

    # ### end Alembic commands ###
