"""Add measurement_system to User model

Revision ID: d2d38616b469
Revises: b3ce282b86ac
Create Date: 2025-07-06 21:25:53.572967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d38616b469'
down_revision = 'b3ce282b86ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measurement_system', sa.String(length=10), nullable=False, server_default='metric'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('measurement_system')

    # ### end Alembic commands ###
