"""Add timezone to User model

Revision ID: eb35a1c585a3
Revises: 22ef89f12932
Create Date: 2025-07-25 21:56:56.328113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb35a1c585a3'
down_revision = '22ef89f12932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=100), nullable=True)) # Add the column as nullable initially

    # Update existing rows with a default or calculated timezone value
    op.execute("UPDATE users SET timezone = 'UTC' WHERE timezone IS NULL") # Using op.execute to run a raw SQL query
    # Or, if you need to calculate for each user based on existing data:
    # op.execute("UPDATE users SET timezone = 'America/New_York' WHERE country = 'USA'")


    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('timezone', existing_type=sa.String(length=100), nullable=False) # Change the column to NOT NULL

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
