"""Add fdc_id and upc to MyFood table

Revision ID: ed46d6d10d28
Revises: 0c464220f242
Create Date: 2025-07-05 21:31:00.081279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed46d6d10d28'
down_revision = '0c464220f242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fdc_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('upc', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_foods', schema=None) as batch_op:
        batch_op.drop_column('upc')
        batch_op.drop_column('fdc_id')

    # ### end Alembic commands ###
